---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# About the Paper

This Readme provides supplementary materials and resources related to the paper:

***"The Standardization of Accounting Language".***

::: {style="text-align: justify"}
[Abstract.]{.smallcaps} The communication of accounting information requires a special vocabulary, and, in specialized languages, standardization is a key to clear communication. We provide the first large-sample evidence on the level, determinants, and implications of accounting terminology standardization for the universe of corporate filings written in English, the lingua franca of capital markets. Three main takeaways emerge from our analyses. First, we describe the use and properties of accounting terminology and find that cognitive and dialectal causes (e.g., accounting systems and English proficiency) are the most important drivers of terminology standardization. Second, the adoption of a new reference framework of accounting terms or tags (i.e., the introduction of IFRS and XBRL) increases standardization but conceals linguistics-related heterogeneities. Third, terminology standardization is negatively associated with both the incompleteness within and differences across accounting databases, consistent with the idea of standardized language being instrumental for users in extracting accounting information and reducing information processing costs.
:::

The complete GitHub repositories consist of 4 parts:

-   **Part 1:** Supplementary Material for the Paper

-   **Part 2:** Pipeline for counting terms in an Annual Report

-   **Part 3:** Accompanying R Packages

    -   **Part 3a**: Count Terms in a Corpus

    -   **Part 3b:** Match Company Names

# Part 1: Supplementary Material for the Paper

In this repository you can find our term and concept list and all the additional list that we publish together with the paper.

The repository can be found here: <https://github.com/TerminologyStandardization/Supplementary>

# Part 2: Pipeline for counting terms in an Annual Report

In this repository we provide a simple pipeline of counting terms in an Annual Report. This pipeline replicates the procedure used in the paper.

The repository can be found here: <https://github.com/TerminologyStandardization/Pipeline>

# Part 3a: Accompanying R Package - Count Terms in a Corpus

This is the package we use for counting the occurrences of of our term list in our annual report corpus.

The package can be found here: <https://github.com/TerminologyStandardization/rTermCount>

# Part 3b: Accompanying R Package - Match Company Names

This is the package we use for matching our annual report data set to Worldscope by company name.

The package can be found here: <https://github.com/TerminologyStandardization/rMatching>
